apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: habit-tracker
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: habit-tracker

  source:
    repoURL: https://github.com/capricarun/habitapp-gitops.git
    targetRevision: main
    path: charts/habit-tracker
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: habit-tracker

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true

    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10
